/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de6;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author honahl
 */
public class Dictionary extends javax.swing.JFrame {

    ArrayList<Word> list = new ArrayList<>();

    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
        khoiTaoTu();
    }

    public void khoiTaoTu() {
        Word w1 = new Word(1, "one", "môt");
        list.add(w1);
        Word w2 = new Word(2, "two", "hai");
        list.add(w2);
        Word w3 = new Word(3, "three", "ba");
        list.add(w3);
        Word w4 = new Word(4, "four", "bốn");
        list.add(w4);
        Word w5 = new Word(5, "five", "năm");
        list.add(w5);
        Word w6 = new Word(6, "six", "sáu");
        list.add(w6);
        Word w7 = new Word(7, "seven", "bảy");
        list.add(w7);
        Word w8 = new Word(8, "eight", "tám");
        list.add(w8);
        Word w9 = new Word(9, "nine", "chín");
        list.add(w9);
        Word w10 = new Word(10, "ten", "mười");
        list.add(w10);
        Word w11 = new Word(11, "eleven", "mười một");
        list.add(w11);
        Word w12 = new Word(12, "twelve", "mười hai");
        list.add(w12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFeng = new javax.swing.JTextField();
        TFvnese = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Badd = new javax.swing.JButton();
        Bsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("TỪ ĐIỂN ");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("EN");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("VN");

        Badd.setBackground(new java.awt.Color(204, 204, 204));
        Badd.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Badd.setText("SEARCH");
        Badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddActionPerformed(evt);
            }
        });

        Bsearch.setBackground(new java.awt.Color(204, 204, 204));
        Bsearch.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Bsearch.setText("ADD");
        Bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(TFeng,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 243,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addGap(11, 11, 11)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(Badd, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(75, 75, 75)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TFvnese, javax.swing.GroupLayout.PREFERRED_SIZE, 243,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Bsearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(19, 19, 19)))
                                .addContainerGap(55, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TFeng, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TFvnese, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Badd, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(71, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BaddActionPerformed
        for (Word word : list) {
            word.hienthi();
        }
        Collections.sort(list, new WordComparator());
        System.out.println("========================================");
        for (Word word : list) {
            word.hienthi();
        }

        if (!TFeng.getText().isEmpty()) {
            int n = search();
            if (n == -1) {
                JOptionPane.showMessageDialog(this, "không tìm được mời bạn bổ sung");
            } else {
                TFvnese.setText(list.get(n).getVn());
            }

        } else {

            JOptionPane.showMessageDialog(this, "ko duoc de trong");
        }

    }// GEN-LAST:event_BaddActionPerformed

    private void BsearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BsearchActionPerformed
        if (!TFeng.getText().isEmpty() && !TFvnese.getText().isEmpty()) {
            Word addWord = new Word(list.size(), TFeng.getText(), TFvnese.getText());
            list.add(addWord);
            Collections.sort(list, new WordComparator());
            System.out.println("========================================");
            for (Word word : list) {
                word.hienthi();
            }
        } else {
            JOptionPane.showMessageDialog(this, "hãy nhập đủ thông tin");
        }
    }// GEN-LAST:event_BsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    public int search() {
        int L = 0;
        int R = list.size() - 1, M;
        while (L <= R) {
            M = (L + R) / 2;
            String word = list.get(M).getEn();
            // System.out.println(TFeng.getText().trim().compareToIgnoreCase(word));
            if (TFeng.getText().trim().compareToIgnoreCase(word) == 0) {
                return M;
            } else if (TFeng.getText().trim().compareToIgnoreCase(word) > 0) {
                L = M + 1;
            } else {
                R = M - 1;
            }
        }
        return -1;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badd;
    private javax.swing.JButton Bsearch;
    private javax.swing.JTextField TFeng;
    private javax.swing.JTextField TFvnese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
