/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author honahl
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        creatContentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "họ và tên", "ngay sinh", "địa chỉ", "Giới Tính", "Phòng Ban", "hệ số lương", "lương CB", "thâm niên", "lương TL"
            }
        ));
        jScrollPane1.setViewportView(TableNhanVien);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("BẢNG DANH SÁCH SINH VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }
    
    public List<NhanVien> readFile(){
        FileReader fileReader = null;
        BufferedReader reader = null;
        List<NhanVien> listNhanVien = null;
        try {

            fileReader = new FileReader("/home/honahl/Documents/finalOopTrain/De2/src/de2/nhanvien.dat");
            reader = new BufferedReader(fileReader);
            listNhanVien = new ArrayList<>();

            String SNhanVien = "";
            while ((SNhanVien = reader.readLine()) != null) {
                String[] TTnhanVien = SNhanVien.split("\\$");
                NhanVien nhanVien = new NhanVien();
                nhanVien.setHoTen(TTnhanVien[0]);
                nhanVien.setGioiTinh(TTnhanVien[1]);
                nhanVien.setDiaChi(TTnhanVien[2]);
                nhanVien.setNgaySinh(TTnhanVien[3]);
                nhanVien.setPhongBan(TTnhanVien[4]);
                nhanVien.setThamNien(Integer.parseInt(TTnhanVien[5]));
                nhanVien.setHeSoLuong(Integer.parseInt(TTnhanVien[6]));
                nhanVien.setLuongCoBan(Integer.parseInt(TTnhanVien[7]));
                listNhanVien.add(nhanVien);
                System.out.println("doc file thanh cong");
            }
            System.out.println("doc file thanh cong");
            fileReader.close();
            reader.close();
        } catch (Exception e) {
            System.out.println("doc file khong thanh cong");
            e.printStackTrace();
        }
        return listNhanVien;
    }
    
    // cách 1 add từng dòng 
    public void creatContentTable() {
        DefaultTableModel model = new DefaultTableModel();
        List<NhanVien> list = readFile();
        if (list != null) {
            for (NhanVien nhanVien : list) {
                Object[] obj = {nhanVien.getHoTen(),nhanVien.getNgaySinh()
                                ,nhanVien.getDiaChi(),nhanVien.getGioiTinh()
                                ,nhanVien.getPhongBan(),nhanVien.getHeSoLuong()
                                ,nhanVien.getLuongCoBan(),nhanVien.getThamNien(),nhanVien.luongThucLinh()};
                model = (DefaultTableModel) TableNhanVien.getModel();
                model.addRow(obj);
            }
        }else{
            JOptionPane.showMessageDialog(this, "doc file khong thanh cong hoac file trong");
        }
    }
    // các 2 tạo rồi add một thể giống anh gì ấy trên mạng 
    public void creatContentTable2() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ho va ten");
        model.addColumn("ngay sinh");
        model.addColumn("dia chi");
        model.addColumn("gioi tinh");
        model.addColumn("phong ban");
        model.addColumn("he so luong");
        model.addColumn("luong co ban");
        model.addColumn("tham nien");
        model.addColumn("Luong TL");
        List<NhanVien> list = readFile();
        if (list != null) {
            for (NhanVien nhanVien : list) {
                Object[] obj = {nhanVien.getHoTen(),nhanVien.getNgaySinh()
                                ,nhanVien.getDiaChi(),nhanVien.getGioiTinh()
                                ,nhanVien.getPhongBan(),nhanVien.getHeSoLuong()
                                ,nhanVien.getLuongCoBan(),nhanVien.getThamNien(),nhanVien.luongThucLinh()};
                model.addRow(obj);
            }
            TableNhanVien.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "doc file khong thanh cong hoac file trong");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
